# epic CI/CD pipeline with github actions

name: my epic pipeline

on: 
  push: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the code 
      uses: actions/checkout@v4

    - name: bump the patch number
      uses: qcastel/github-actions-maven-release@v1.12.0
      with: 
        release-type: patch
        github-token: ${{ secrets.GITHUB_TOKEN }}