# epic CI/CD pipeline with github actions.

name: my epic pipeline

on: 
  push: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the code 
      uses: actions/checkout@v4

    - name: bump the patch number
      uses: qcastel/github-actions-maven-release@v1.12.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        access-token: ${{ secrets.GITHUB_TOKEN }}
        version-major: 1
        version-minor: 0