# epic CI/CD pipeline with github actions

name: my epic pipeline

on: 
  push: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the code 
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        
    - name: bump the patch number
      uses: qcastel/github-actions-maven-release@v1.12.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        access-token: ${{ secrets.GITHUB_TOKEN }}
        version-major: 1
        version-minor: 0